### ISSUE TITLE
something goes wrong when doing authentication. error code:400, error message:auth failed for user:

### ISSUE THREAD

**Issue by liuxinwang** [haozi3156666/canal-python#4]
版本：canal 1.1.4
client.check_valid(username=b'', password=b'') 这里的username 和 password我不清楚应该填写哪个。

经过测试，如果canal server用户非local方式启动是可以正常运行，local方式启动的会有问题。

**Comment by cslingjun** [comment]
> 版本：canal 1.1.4
> client.check_valid(username=b'', password=b'') 这里的username 和 password我不清楚应该填写哪个。
> 
> 经过测试，如果canal server用户非local方式启动是可以正常运行，local方式启动的会有问题。

我也遇到这个问题了 ，解决了么

**Comment by bithaolee** [comment]
username 和 password 都是在 canal server 配置文件中配置的，默认应该为空

**Comment by imjackoe** [comment]
在admin里canal server的配置文件注释以下两行就可以
#canal.user = canal
#canal.passwd = E3619321C1A937C46A0D8BD1DAC39F93B27D4458
